import JSZip from "jszip";
import { createClient } from "@/lib/supabase/server";
import { CurriculumSchema } from "@/lib/schema";
import {
  generateHandoutsDocx,
  generateLessonPlansDocx,
} from "@/lib/export/docx";

export const maxDuration = 60;

export async function POST(req: Request) {
  const body = (await req.json()) as { projectId?: string };
  const projectId = body.projectId;
  if (!projectId) return new Response("projectId required", { status: 400 });

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return new Response("Unauthorized", { status: 401 });

  const { data: project } = await supabase
    .from("projects")
    .select("id, user_id, current_snapshot_id")
    .eq("id", projectId)
    .single();
  if (!project) return new Response("Project not found", { status: 404 });
  if (!project.current_snapshot_id)
    return new Response("No snapshot to export yet", { status: 400 });

  const { data: snap } = await supabase
    .from("snapshots")
    .select("id, content")
    .eq("id", project.current_snapshot_id)
    .single();
  if (!snap) return new Response("Snapshot not found", { status: 404 });

  const curriculum = CurriculumSchema.parse(snap.content);

  const [lessonPlans, handouts] = await Promise.all([
    generateLessonPlansDocx(curriculum),
    generateHandoutsDocx(curriculum),
  ]);

  const zip = new JSZip();
  zip.file("lesson-plans.docx", lessonPlans);
  zip.file("handouts.docx", handouts);
  zip.file(
    "README.txt",
    `${curriculum.meta.title}\nTheme: "${curriculum.meta.theme.name}"\n\nGenerated by the BreakFree Words Unlocked Customizer.\nSnapshot: ${snap.id}\n`,
  );
  const zipBuf = await zip.generateAsync({ type: "uint8array" });

  const storagePath = `${user.id}/${project.id}/${snap.id}.zip`;
  const { error: uploadError } = await supabase.storage
    .from("bundles")
    .upload(storagePath, zipBuf, {
      contentType: "application/zip",
      upsert: true,
    });
  if (uploadError) {
    return new Response(`Upload failed: ${uploadError.message}`, {
      status: 500,
    });
  }

  await supabase.from("bundles").insert({
    project_id: project.id,
    snapshot_id: snap.id,
    storage_path: storagePath,
    format: "docx-zip",
  });

  const { data: signed } = await supabase.storage
    .from("bundles")
    .createSignedUrl(storagePath, 600);

  return Response.json({
    ok: true,
    url: signed?.signedUrl ?? null,
    storagePath,
  });
}
